name: Benchmarks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Run benchmarks
        run: deno bench --unstable-kv --json > benchmark-results.json

      - name: Convert benchmark results
        run: deno run --allow-read benchmarks/utils/convert_bench_results.ts benchmark-results.json > benchmark-results-converted.json

      - name: Store and compare benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Benchmark"
          tool: "customSmallerIsBetter"
          output-file-path: benchmark-results-converted.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks-data"
          auto-push: ${{ github.event_name == 'push' }}
          comment-on-alert: true
          summary-always: true
          alert-threshold: "120%"
          comment-always: ${{ github.event_name == 'pull_request' }}
          fail-on-alert: false
